### PR TITLE
Update SamplesOfUsageTest.java

### PR DESCRIPTION
**Pull request by Stephan972**
Make it clearer where test code appears.

### CODE REVIEW

**Comment by woprzech** [comment]
Hello, thank you for your PR. Good idea to clarify sample of usages but maybe instead of comments it's better to write simple meaningfull assertions in each test. For example
```java 
    @Test
    @Parameters
    public void paramsInDefaultMethod(String text, Integer length) {
        assertThat(text).hasSize(length);
    }
    private Object parametersForParamsInDefaultMethod() {
        return new Object[]{new Object[]{"some", 4}, new Object[]{"any", 3}};
    }
```

What do you think about it?

**Comment by Stephan972** [comment]
Indeed, simple assertions maybe meaningfull. 

However, parameters named `p1`, `p2` or `param1`... may need to be renamed for creating interesting assertions.

Imagine:
    assertThat(p1).hasSize(p2); // ??

**Comment by woprzech** [comment]
Feel free to rename params method as in my example :wink:

**Comment by michal-lipski** [comment]
@Stephan972 I will close this PR. You are welcome to open another one if you want to improve testCases names or parameters names.

**Pull request closed without merging**
