### PR TITLE
@Nullable created -  to allows test null values defined as a String array in @Parameters anotation + BidDecimal autocast

### PR DESCRIPTION
**Pull request by peterjurkovic**
Currently is not possible to test null values defined as a String array in @Parameters. The values are converted to a String representation. This is in quite a lot of situation unwanted. Using @Nullable annotation will be null values converted to the null instead of String "null".

```java
@Test
@Parameters({" null "})
public void shouldBeNull(@Nullable String value) {
    assertThat(value).isNull();
}
```
**Edit:**

Would be nice to have BigDecimal auto conversion to make tests a bit more concise.
**Before**
```java
@Test
@Parameters({"1.00, 0.20"})
public void shouldCalculateVat(String strPrice, String expectedVat) {
		BigDecimal price = new BigDecimal( strPrice );

		BigDecimal actualVat = sut.calculateVat( price );

		assertThat( actualVat ).isEqualTo( expectedVat );
}
```

**Now**

```java
@Test
@Parameters({"1.00, 1.25"})
public void shouldConvertToBigDecimalType(BigDecimal first, BigDecimal second) {
        assertThat(first).isEqualTo( new BigDecimal("1.00") );
        assertThat(second).isEqualTo( new BigDecimal("1.25"));
 }
`

### CODE REVIEW

**Comment by jrmichael** [comment]
I like the `@Nullable` annotation.

When it comes to BigDecimal conversion I think it should also be implemented as a `@Converter`.

Can you do it @peterjurkovic ?
And one more thing: extract tests for nullable and bigdecimal to separate test classes.

**Comment by peterjurkovic** [comment]
@jrmichael thanks for your feedback, Sure, I can do it.

**Comment by peterjurkovic** [comment]
By the way, why do you think that `BigDecimal` should be also implemented as a custom `@Param`? In my opinion is better to have build-in BigDecimal conversion support, this does not affect existing code and it is a bit more handy and concise.

**Comment by jrmichael** [comment]
I was worried about people complaining about different or unknown precision. Therefore I did not want it to be a part of JUnitParams. Now that I learned that precision is derived from the number of digits after decimal separator I am not complaining anymore. Plus it is only 3 line ;)

**Pull request merged**
