### PR TITLE
Added @Nullable support for all other Object types

### PR DESCRIPTION
**Pull request by peterjurkovic**
`@Nullable` is quite handy annotation, but the current version just supports `java.lang.String`. In this pull request I have added also support for the other types.

The other change is deprecation of `nullIdentifier()` and was added  `value()`alias. A user can directly change the identifier by specifying `@Nullable("myNull")`. The old variant  `@Nullable(nullIdentifier = "myNull")`  is quite verbose.

### CODE REVIEW

**Comment by jrmichael** [comment]
Thanks for this PR @peterjurkovic 
We reviewed it and decided to go for a different implementation. However we reused your tests.

We decided not to introduce `value()`. We think that changing default identifier is quite a rare case and it should be clearly visible that you are doing something strange.

**Comment by peterjurkovic** [comment]
@jrmichael thanks for the feedback.
One more think. Would be good also reuse [SamplesOfUsageTest.java](https://github.com/Pragmatists/JUnitParams/pull/111/files#diff-967713a5bbc51f788c3c02ce05c10477) I've added a few more samples to given class demonstrating `@Nullable` features.

**Comment by RunninglVlan** [comment]
>@jrmichael: We reviewed it and decided to go for a different implementation.

What is this different implementation? There is still no support for Nullable Objects (other than String).

**Comment by peterjurkovic** [comment]
Guys any update on this? Would be nice to have it.

**Comment by woprzech** [comment]
There are some examples with nullable values for different classes than `java.lang.String`:
[NullableConverterTest.java](https://github.com/Pragmatists/JUnitParams/blob/master/src/test/java/junitparams/converters/NullableConverterTest.java)

Is something missing in current implementation?

**Comment by peterjurkovic** [comment]
Yeah, I know, it was my PR. Currently is supported just `String` this PR supposes add support `@Nullable` for all the other java types.

**Comment by woprzech** [comment]
Yes, but it's file from current version of JUnitParams :)
As @jrmichael said : `We reviewed it and decided to go for a different implementation. However we reused your tests.`  - we took your tests and made different implementation.

So, it's been possible to use `@Nullable` with all java types since `1.1.0` version

**Comment by woprzech** [comment]
I've just noticed that we didn't place any information about this fix in `Release notes` so it might have been confusing :disappointed: Sorry.

**Comment by peterjurkovic** [comment]
Ou, really :relaxed: that are great news. I was actually checking `Release notes` but was nothing there about `@Nullable`. Thanks you.

**Pull request closed without merging**
