### PR TITLE
Add method for creating combinations of arrays and a @CombinedParamet…

### PR DESCRIPTION
**Pull request by piekarskim**
…ers to use it.

Solution to Issue #1 

That's probably not the best way to implement this functionality... 
- Should I add separate strategies for generating parameters or add the logic to the existing ones?
- There's probably a lot of oom for improvement in method/variable names
- What about the annotation name?
- Should @CombinedParameters take values (i.e. it's enough to annotate a test method with it alone) or should it take them from @Parameters (i.e it's necessary to annotate a method with both @CombinedParameters and @Parameters)?

Looking forward to your comments :)

### CODE REVIEW

**Comment by piekarskim** [comment]
Hi guys,

Could you comment if it's a good/bad way to go?

Cheers

**Comment by jrmichael** [comment]
Sorry @piekarskim. I am pretty busy these days. Will check it out next week.

**Comment by jrmichael** [comment]
Sorry for the long delay.

I have merged PR#82 which introduces `@CustomParameters` annotation. It is a way to create new annotations with custom behavior for parameters generation/conversion without changing the JUnitParams internals.
Can you refactor `@CombinedParameters` to use this approach? 
- implement `ParametersProvider` instead of `ParametrizationStrategy`
- annotate `@CombinedParameters` with `@CustomParameters`
- move it to `junitparams.custom` package

In future we will think about extracting builtin CustomParameters implementations into a separate library.

Let me know if you don't have time for this and I will refactor it myself.

BR

**Comment by piekarskim** [comment]
No worries, I'll find some time :)

**Comment by piekarskim** [comment]
Refactored, could you please take a look?

**Comment by jrmichael** [comment]
Great job @piekarskim 
Thanks a lot.

**Pull request merged**
