### PR TITLE
Closes #70 - @TestCaseName not displaying the contents of an array pa…

### LINKED ISSUE #70: @TestCaseName not displaying the contents of an array passed as an argument
Contents of an array passed as one of test parameters are currently not being displayed in the test's description generated by `@TestCaseName` annotation.

Example:

    private static final File JAVA_DIRECTORY = get("src/main/java/").toFile();
	private static final String[] NOT_ACCEPTABLE_IN_JAVA_DIRECTORY = {"groovy", "css", "html"};

	public Object[] filesNotAcceptedInDirectories() {
		return $(
				$(JAVA_DIRECTORY, NOT_ACCEPTABLE_IN_JAVA_DIRECTORY)
		);
	}

	@Test
	@Parameters(method = "filesNotAcceptedInDirectories")
	@TestCaseName("Verify that no files with extensions {1} are present in directory {0}")
	public void verifyFilesArePlacedInAppropriateDirectories(File directory, String[] unacceptableFiles) {
		assertThat(listFiles(directory, unacceptableFiles, true)).isEmpty();
	}

should display as:

`Verify that no files with extensions [groovy, css, html] are present in directory src\main\java`

but what we currently get is:
`Verify that no files with extensions String[] are present in directory src\main\java`

### PR DESCRIPTION
**Pull request by piekarskim**
…ssed as an argument

### CODE REVIEW

**Comment by adammichalik** [comment]
Unfortunately, this won't work with arrays of primitives - `Arrays.toString()` has separate overloaded methods for each primitive array type and trying to cast `int[]` to `Object[]` will fail.

**Comment by piekarskim** [comment]
:+1: Missed that. Is it ok for me to use Apache Commons Lang?

**Comment by adammichalik** [comment]
Right now JUnitParams has no dependencies, so I don't think it's acceptable to introduce one just for this purpose (and require users to have it as their transitive dependency). But let's wait for Pragmatists to reply.

**Comment by jrmichael** [comment]
We would like to keep the list of dependencies as small as possible. 
@piekarskim try implementing a simple version of `ArrayUtils.toString()`

**Comment by piekarskim** [comment]
:+1: Done

**Comment by jrmichael** [comment]
thx @piekarskim

**Comment by ffbit** [comment]
I'm impatiently looking forward to a new release with this feature. 
Thanks in avance.

**Pull request merged**
