### PR TITLE
Lost custom annotations on parameterized methods

### PR DESCRIPTION
**Pull request by artkoshelev**
Hi, i've faced a problem with annotations on parameterized methods. Here is a test reproducing it.

### CODE REVIEW

**Comment by artkoshelev** [comment]
@jrmichael can you look at this please?

**Comment by woprzech** [comment]
@artkoshelev We are working on it now. I suppose that we deliver fix for the issue soon.

**Comment by jrmichael** [comment]
Hi @artkoshelev 

We tried to implement it together with @woprzech 
It turned out to be impossible with current version of JUnit. The only place to pass annotations is JUnits `Description` object. However it has all the constructors private and all the fields final. Since we have to pass uniqueMethodId and custom name, we cannot add annotations anymore. We are bound to use [this method](https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runner/Description.java#L109). We can of course use reflection to construct this object but it may have a significant performance impact.

Maybe you can describe us your use case for custom annotations and we can think of a workaround. Why do you need them? What is your goal? What are you building? etc.

**Comment by artkoshelev** [comment]
I was writing mobile app tests with appium and allure frameworks when faced this issue. I use `@Feature` and `@Story` annotations on test methods to build nice reports with Allure framework. While searching for solution i tried to fix it in your code, but faced same limitations in JUnit. Since JUnit 4.x branch is no longer developing i don't think solution can be found except the hacky ones with bytecode modifications.

So, i ended up with standard JUnit parametrization for my task, despite the fact your solution is really cool to work with. But if you going to work with new JUnit (which was completely rewritten), that case is probably the one to keep in mind.

**Comment by jrmichael** [comment]
@artkoshelev We won't implement a fix for this issue as I described it before.

We think that you can still use JUnitParams and `@Story / @Feature`  annotations by adding them on classes instead of methods.

**Pull request closed without merging**
